"""add attempt number and time taken

Revision ID: a894e10e085f
Revises: 390cab0d1c7c
Create Date: 2026-08-03 16:43:18.969888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a894e10e085f'
down_revision: Union[str, Sequence[str], None] = '390cab0d1c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('time_taken_seconds', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempts_user_id_fkey'), 'quiz_attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quiz_attempts_quiz_id_fkey'), 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_attempts', 'time_taken_seconds')
    # ### end Alembic commands ###
