"""check

Revision ID: bd5e4c3d8dab
Revises: 9e4bb7c629b3
Create Date: 2026-08-03 16:13:41.605975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5e4c3d8dab'
down_revision: Union[str, Sequence[str], None] = '9e4bb7c629b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
